---
- name: set Containerd proxy as needed
  become: true
  ansible.builtin.template:
    src: "containerd-rke2-http-proxy.conf"
    dest: "/etc/default/rke2-{{ INSTALL_RKE2_TYPE }}"
    owner: root
    group: root
    mode: '0644'
