## Main Tasks Entrypoint
---
- name: Prerequierments
  include_tasks: prerequirements.yaml

- name: set Containerd proxy if needed
  include_tasks: containerdProxy.yaml
  when: set_proxy == true

- name: RKE2 Script
  become: true  
  ansible.builtin.shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE={{ INSTALL_RKE2_TYPE }} INSTALL_RKE2_VERSION={{ INSTALL_RKE2_VERSION }} INSTALL_RKE2_CHANNEL_URL={{ INSTALL_RKE2_CHANNEL_URL }} INSTALL_RKE2_CHANNEL={{ INSTALL_RKE2_CHANNEL }} INSTALL_RKE2_METHOD={{ INSTALL_RKE2_METHOD}} sh -

- name: Ensure /etc/rancher/rke2 directory exists
  become: true
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
- debug:
    msg: "node type {{ first_server_node }}"

- name: server block
  block:
    - name: set RKE2 config.yaml
      become: true
      ansible.builtin.template:
        src: first-server-config.yaml
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'

    - name: start RKE2 first server node
      become: true
      ansible.builtin.systemd:
        name: rke2-server.service
        state: started
        enabled: true

    - name: register cluster join token
      become: true
      ansible.builtin.command: cat /var/lib/rancher/rke2/server/node-token
      register: cluster_token_store

    - name: store cluster join token localy
      local_action: copy content="{{ cluster_token_store.stdout_lines[0] }}" dest="/tmp/cluster-token" force="true"
  
    - name: register kubeconfig
      become: true
      ansible.builtin.command: cat /etc/rancher/rke2/rke2.yaml
      register: kube_config

    - name: store kubeconfig localy
      local_action: copy remote_src="/etc/rancher/rke2/rke2.yaml" dest="./kubeconfig" force="true"
  when:
  - first_server_node
  - INSTALL_RKE2_TYPE == "server"

- name: copy token to nodes
  become: true
  ansible.builtin.copy:
    src: /tmp/cluster-token
    dest: /tmp/cluster-token
    owner: root
    group: root
    mode: '0644'
  register: cluster_token_tmp

- name: register cluster token
  ansible.builtin.command: cat /tmp/cluster-token
  register: cluster_token

- debug:
    msg: "file exists {{ cluster_token }}"

- name: 'oth server block'
  block:
    - name: set RKE2 config.yaml
      become: true
      ansible.builtin.template:
        src: server-join-config.yaml
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'

    - name: start RKE2 server on node
      become: true
      ansible.builtin.systemd:
        name: rke2-server.service
        state: started
        enabled: true
  when:
    - not first_server_node
    - INSTALL_RKE2_TYPE == "server"

- block:
    - name: set RKE2 config.yaml
      become: true
      ansible.builtin.template:
        src: agent-join-config.yaml
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'

    - name: start RKE2 agent on node
      become: true
      ansible.builtin.systemd:
        name: rke2-agent.service
        state: started
        enabled: true

  when:
    - INSTALL_RKE2_TYPE == "agent"
