## Handlers RKE2 Services
---
- name: "rke2_service_handler"
  become: true
  ansible.builtin.systemd:
    name: "rke2-{{ RKE2_INSTALL_VALUES.INSTALL_RKE2_TYPE }}.service"
    state: started
    enabled: true
    daemon-reload: yes
