---
write-kubeconfig-mode: "{{ write_kubeconfig_mode }}"
disable:
{% for result in disable %}
  - {{ result }}
{% endfor %}
node-ip: "{{ node_ip }}"
tls-san:
{% for san in tls_san %}
  - {{ san }}
{% endfor %}
cluster-cidr: "{{ cluster_cidr }}"
service-cidr: "{{ service_cidr }}"
