---
write-kubeconfig-mode: "{{ write_kubeconfig_mode }}"
disable: "{{ disable }}"
node-ip: "{{ node_ip }}"
tls-san: "{{ tls_san }}"
cluster-cidr: "{{ cluster_cidr }}"
service-cidr: "{{ service_cidr }}"
