---
write-kubeconfig-mode: "{{ write_kubeconfig_mode }}"
disable:
{% for result in disable %}
  - {{ result }}
{% endfor %}
node-ip: "{{ node_ip }}"
tls-san: "{{ tls_san | to_nice_yaml }}"
cluster-cidr: "{{ cluster_cidr }}"
service-cidr: "{{ service_cidr }}"
